name: Build and deploy Node.js docker image - firstmate-git-manager
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Bump version and set tag
        id: bump_version
        run: |
          LATEST_TAG=$( git describe --tags --abbrev=0 )
          wget -O semver  https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x ./semver
          VERSION=$( ./semver bump patch $( git describe --tags --abbrev=0 ) )
          git tag $VERSION
          echo "LATEST_TAG=$(echo $LATEST_TAG)" >> $GITHUB_ENV
          echo "VERSION=$(echo $VERSION)" >> $GITHUB_ENV
          echo "::set-output name=new_tag::$(echo $VERSION)"
      - name: push tag
        run: git push --tag

